stages:

  data_ingestion:
    cmd: python -m crop_recommendation.pipeline.01_data_ingestion_pipeline
    deps:
      - data/raw/Crop_recommendation.csv
      - config/config.yaml
      - src/crop_recommendation/components/data_ingestion.py
      - src/crop_recommendation/configuration/config.py
      - src/crop_recommendation/entity/config_entity.py
    outs:
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv


  data_validation:
    cmd: python -m crop_recommendation.pipeline.02_data_validation_pipeline
    deps:
      - artifacts/data_ingestion/train.csv
      - config/config.yaml
      - config/schema.yaml
      - src/crop_recommendation/components/data_validation.py
      - src/crop_recommendation/configuration/config.py
      - src/crop_recommendation/entity/config_entity.py
    outs:
      - artifacts/data_validation/status.txt


  data_preprocessing:
    cmd: python -m crop_recommendation.pipeline.03_data_preprocessing_pipeline
    deps:
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
      - artifacts/data_validation/status.txt
      - config/config.yaml
      - src/crop_recommendation/components/data_preprocessing.py
      - src/crop_recommendation/configuration/config.py
      - src/crop_recommendation/entity/config_entity.py
    outs:
      - artifacts/data_preprocessing/train_processed.csv
      - artifacts/data_preprocessing/test_processed.csv
      - artifacts/data_preprocessing/scaler.pkl

  model_trainer:
    cmd: python -m crop_recommendation.pipeline.04_training_pipeline
    deps:
      - src/crop_recommendation/pipeline/04_training_pipeline.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_preprocessing/train_processed.csv
      - artifacts/data_preprocessing/test_processed.csv
    outs:
      - artifacts/model_trainer/model.pkl